PRAGMA foreign_keys = OFF;
DROP INDEX IF EXISTS idx_maintenance_job_time;
DROP TABLE IF EXISTS maintenance_runs;
DROP INDEX IF EXISTS idx_vitals_route_hour;
DROP TABLE IF EXISTS vitals_hourly;
DROP INDEX IF EXISTS idx_owner_audit_time;
DROP INDEX IF EXISTS idx_owner_audit_target;
DROP TABLE IF EXISTS owner_audit_log;
DROP INDEX IF EXISTS idx_email_event_received;
DROP INDEX IF EXISTS idx_email_event_message;
DROP TABLE IF EXISTS email_delivery_events;
DROP INDEX IF EXISTS idx_outbox_contact;
DROP INDEX IF EXISTS idx_outbox_ready;
DROP TABLE IF EXISTS notification_outbox;
DROP INDEX IF EXISTS idx_contact_inbox_unread;
DROP INDEX IF EXISTS idx_contact_ip_created;
DROP INDEX IF EXISTS idx_contact_created;
DROP INDEX IF EXISTS idx_contact_email;
DROP TABLE IF EXISTS contact_submissions;
PRAGMA foreign_keys = ON;
